// 示範資料：6 筆虛構資源，供展示與測試使用（第 1 筆改寫自 doc/resource-schema.md 第十節）
// 機構、人名、電話、網址皆為虛構：名稱含「示範／範例」、電話為 0000 號段、網址為 example.com
// 每筆帶 isDemo: true，可由 resourceService.removeDemoResources() 一鍵移除
//
// 組成（tests/demoResources.test.js 會逐項檢查）：
//   探索頁顯示 3 筆：黃燈（板橋）、綠燈（中和）、綠燈（臺北大安），分屬不同行政區
//   探索頁不顯示 3 筆：暫停、風險紅燈、合作尚未確認各一筆

const CRITERIA_ALL_GREEN = {
  management: "green",
  insurance: "green",
  environment: "green",
  complaints: "green",
  staffQualification: "green",
};

const SAME_AS_PUBLIC = { sameAsPublic: true, name: null, phone: null, emailOrLine: null };

export const DEMO_RESOURCES = [
  // 1. 板橋｜黃燈｜口頭確認｜常態每週 → 探索頁顯示（轉介時提示需陪同）
  {
    id: "7c1e2a40-5b3d-4f1a-9e2c-1a2b3c4d5e6f",
    isDemo: true,
    code: "Res001",
    verifiedBy: { type: "team", name: "王示範" },
    lastVerifiedAt: "2026-10-01",
    nextVerifyAt: "2027-01-01",
    status: "active",
    pauseReason: null,
    resumeAt: null,
    seasonalNote: null,
    createdAt: "2025-04-01T09:00:00+08:00",
    updatedAt: "2026-10-01T09:00:00+08:00",

    name: "湳興河濱長者健走班",
    organization: "示範社區發展協會",
    description: "健走老師每週二早上 7 點於河濱公園帶領 1 小時團體步行，適合能自行行走的社區長者。",
    prescriptionTypes: ["health", "social"],
    needTags: ["exercise", "companionship"],
    needTagOther: null,
    staff: [
      { name: "陳範例老師", role: "帶班老師", license: "國民體適能指導員", experience: "帶領長者運動 5 年" },
    ],
    capacity: { type: "limited", limit: 20 },
    availability: { type: "available", slots: 6, nextBatch: null },
    schedule: {
      type: "regular",
      frequency: "weekly",
      weekdays: [2],
      monthDays: [],
      startTime: "07:00",
      endTime: "08:00",
    },
    placeName: "河濱公園入口",
    address: { zip: "220", city: "新北市", district: "板橋區", detail: "示範路 1 號旁" },
    geo: { lat: 25.0, lng: 121.45 },

    riskLevel: "yellow",
    riskCriteria: {
      management: "green",
      insurance: "green",
      environment: "yellow",
      complaints: "green",
      staffQualification: "green",
    },
    highRisk: { isHighRisk: false, types: [] },
    riskChangeNote: "年度複評：河濱步道部分路段不平整，環境安全由綠燈調整為黃燈",

    ageGroups: ["senior"],
    identities: ["all"],
    identityOther: null,
    notSuitableFor: "無法自行行走者",
    participation: "walk_in",
    participationOther: null,
    languages: ["mandarin", "taiwanese"],
    indigenousTribe: null,
    languageOther: null,
    transport: ["public_transit"],
    transportNote: { publicTransit: "捷運站步行 10 分鐘", shuttle: null, other: null },
    accessibility: ["senior_friendly"],
    accessibilityOther: null,
    fee: { type: "free", detail: null },
    notice: "請穿運動鞋並自備水壺",

    partnership: "verbal",
    publicContact: { name: "林示範", phone: "02-0000-0001", emailOrLine: "demo01@example.com" },
    adminContact: SAME_AS_PUBLIC,
    followUpMethods: ["manager_contact"],
    followUpOther: null,
    links: ["https://example.com/demo-walking"],

    keywords: ["運動", "步行", "長者", "免費"],
    scenarios: "適合醫師建議多運動、但不知道附近哪裡可以去的長者",
  },

  // 2. 中和｜綠燈｜正式合作｜常態每週一三五 → 探索頁顯示
  {
    id: "d3a1f0b2-1c4e-4a6b-8d2f-0a1b2c3d4e02",
    isDemo: true,
    code: "Res002",
    verifiedBy: { type: "provider", name: "陳範例" },
    lastVerifiedAt: "2026-09-01",
    nextVerifyAt: "2027-03-01",
    status: "active",
    pauseReason: null,
    resumeAt: null,
    seasonalNote: null,
    createdAt: "2025-03-01T10:00:00+08:00",
    updatedAt: "2026-09-01T10:00:00+08:00",

    name: "範例里社區共餐食堂",
    organization: "範例食物銀行協會",
    description: "每週一、三、五中午於里民活動中心提供共餐，經濟弱勢者可申請餐費補助並領取食物包。",
    prescriptionTypes: ["basic_support", "social"],
    needTags: ["food", "financial_aid", "companionship"],
    needTagOther: null,
    staff: [
      { name: "陳範例", role: "餐食督導", license: "營養師", experience: "社區供餐規劃 8 年" },
      { name: "黃示例", role: "志工隊長", license: "食品衛生講習結業", experience: "共餐志工 3 年" },
    ],
    capacity: { type: "limited", limit: 40 },
    availability: { type: "available", slots: 12, nextBatch: null },
    schedule: {
      type: "regular",
      frequency: "weekly",
      weekdays: [1, 3, 5],
      monthDays: [],
      startTime: "11:30",
      endTime: "13:00",
    },
    placeName: "範例里民活動中心 1 樓",
    address: { zip: "235", city: "新北市", district: "中和區", detail: "範例街 12 號" },
    geo: { lat: 24.9993, lng: 121.499 },

    riskLevel: "green",
    riskCriteria: CRITERIA_ALL_GREEN,
    highRisk: { isHighRisk: false, types: [] },
    riskChangeNote: "年度複評，五項條件皆維持綠燈",

    ageGroups: ["adult", "senior"],
    identities: ["living_alone", "chronic"],
    identityOther: null,
    notSuitableFor: "需特殊治療飲食（如流質、管灌）者",
    participation: "registration",
    participationOther: null,
    languages: ["mandarin", "taiwanese"],
    indigenousTribe: null,
    languageOther: null,
    transport: ["dropoff", "public_transit"],
    transportNote: { publicTransit: "公車範例站下車步行 3 分鐘", shuttle: null, other: null },
    accessibility: ["barrier_free", "senior_friendly"],
    accessibilityOther: null,
    fee: { type: "subsidized", detail: "每餐 50 元；中低收入戶、獨居長者經評估可全額補助" },
    notice: "首次參加請攜帶身分證件辦理登記，自備環保餐具",

    partnership: "formal",
    publicContact: { name: "陳範例", phone: "02-0000-0002", emailOrLine: "LINE：demo_meal" },
    adminContact: { sameAsPublic: false, name: "張範本", phone: "02-0000-0020", emailOrLine: "admin02@example.com" },
    followUpMethods: ["provider_contact", "report_form"],
    followUpOther: null,
    links: ["https://example.com/demo-meal"],

    keywords: ["共餐", "餐費補助", "食物包", "獨居"],
    scenarios: "適合三餐不定、經濟有壓力，或平常一個人吃飯想找人作伴的長者",
  },

  // 3. 臺北大安｜綠燈（高風險情境但有證照）｜正式合作｜梯次性 → 探索頁顯示
  {
    id: "d3a1f0b2-1c4e-4a6b-8d2f-0a1b2c3d4e04",
    isDemo: true,
    code: "Res003",
    verifiedBy: { type: "team", name: "王示範" },
    lastVerifiedAt: "2026-08-20",
    nextVerifyAt: "2027-02-20",
    status: "active",
    pauseReason: null,
    resumeAt: null,
    seasonalNote: null,
    createdAt: "2025-08-20T09:30:00+08:00",
    updatedAt: "2026-08-20T09:30:00+08:00",

    name: "範例照顧者喘息支持團體",
    organization: "範例家庭照顧者關懷協會",
    description: "由諮商心理師帶領的 8 週照顧者支持團體，每週六上午分享照顧經驗、學習壓力調適。",
    prescriptionTypes: ["basic_support", "health"],
    needTags: ["caregiver_support", "mental"],
    needTagOther: null,
    staff: [
      { name: "許範例", role: "團體帶領者", license: "諮商心理師", experience: "照顧者團體帶領 7 年" },
      { name: "吳示範", role: "協同帶領者", license: "社會工作師", experience: "長照個案管理 4 年" },
    ],
    capacity: { type: "limited", limit: 12 },
    availability: { type: "full", slots: 0, nextBatch: "2027 年 1 月第二梯次，12 月開放報名" },
    schedule: {
      type: "batch",
      startDate: "2026-10-03",
      endDate: "2026-11-21",
      weekdays: [6],
      startTime: "09:30",
      endTime: "11:30",
    },
    placeName: "範例協會 2 樓團體室",
    address: { zip: "106", city: "臺北市", district: "大安區", detail: "範例路二段 8 號 2 樓" },
    geo: { lat: 25.0264, lng: 121.5435 },

    riskLevel: "green",
    riskCriteria: CRITERIA_ALL_GREEN,
    highRisk: { isHighRisk: true, types: ["psychological"] },
    riskChangeNote: "屬心理服務高風險情境，帶領者具諮商心理師證照，人員資格維持綠燈",

    ageGroups: ["adult", "senior"],
    identities: ["caregiver"],
    identityOther: null,
    notSuitableFor: "目前有自傷意念者，請先轉介專業心理治療",
    participation: "referral_only",
    participationOther: null,
    languages: ["mandarin"],
    indigenousTribe: null,
    languageOther: null,
    transport: ["public_transit"],
    transportNote: { publicTransit: "捷運範例站 4 號出口步行 7 分鐘", shuttle: null, other: null },
    accessibility: ["barrier_free", "dementia_friendly"],
    accessibilityOther: null,
    fee: { type: "free", detail: null },
    notice: "團體進行期間可提供被照顧者臨時托顧，請於報名時告知",

    partnership: "formal",
    publicContact: { name: "許範例", phone: "02-0000-0004", emailOrLine: "demo04@example.com" },
    adminContact: { sameAsPublic: false, name: "鄭示例", phone: "02-0000-0040", emailOrLine: "admin04@example.com" },
    followUpMethods: ["provider_contact", "manager_contact"],
    followUpOther: null,
    links: ["https://example.com/demo-caregiver"],

    keywords: ["照顧者", "喘息", "支持團體", "壓力"],
    scenarios: "適合長期照顧家人、感到疲憊或孤單，想找同樣處境的人聊聊的照顧者",
  },

  // 4. 板橋｜綠燈｜正式合作｜暫停 → 探索頁不顯示（暫停中）
  {
    id: "d3a1f0b2-1c4e-4a6b-8d2f-0a1b2c3d4e06",
    isDemo: true,
    code: "Res004",
    verifiedBy: { type: "team", name: "林示例" },
    lastVerifiedAt: "2026-06-01",
    nextVerifyAt: "2026-12-01",
    status: "paused",
    pauseReason: "志工修繕團隊人力調整中",
    resumeAt: "2027-01-05",
    seasonalNote: null,
    createdAt: "2025-02-01T10:00:00+08:00",
    updatedAt: "2026-09-20T10:00:00+08:00",

    name: "示範居家安全修繕服務",
    organization: "示範社區營造協會",
    description: "志工到府評估居家安全，協助加裝扶手、止滑條等簡易修繕，並提供住宅改善補助諮詢。",
    prescriptionTypes: ["basic_support"],
    needTags: ["housing", "home_support"],
    needTagOther: null,
    staff: [
      { name: "何範例", role: "修繕志工隊長", license: "室內裝修工程管理乙級", experience: "居家修繕 12 年" },
    ],
    capacity: { type: "limited", limit: 8 },
    availability: { type: "realtime", slots: 0, nextBatch: null },
    schedule: {
      type: "regular",
      frequency: "weekly",
      weekdays: [3, 4],
      monthDays: [],
      startTime: "09:00",
      endTime: "16:00",
    },
    placeName: "到府服務（以協會辦公室為聯絡據點）",
    address: { zip: "220", city: "新北市", district: "板橋區", detail: "範例路 88 號 1 樓" },
    geo: { lat: 25.0117, lng: 121.4637 },

    riskLevel: "green",
    riskCriteria: CRITERIA_ALL_GREEN,
    highRisk: { isHighRisk: false, types: [] },
    riskChangeNote: "補足公共意外險後由黃燈調整為綠燈",

    ageGroups: ["senior"],
    identities: ["disability", "living_alone"],
    identityOther: null,
    notSuitableFor: "需結構補強或大型改建的房屋",
    participation: "referral_only",
    participationOther: null,
    languages: ["mandarin", "taiwanese"],
    indigenousTribe: null,
    languageOther: null,
    transport: ["other"],
    transportNote: { publicTransit: null, shuttle: null, other: "到府服務，民眾不需前往" },
    accessibility: ["senior_friendly", "dementia_friendly"],
    accessibilityOther: null,
    fee: { type: "subsidized", detail: "材料費依實支，低收入戶與身障者可申請全額補助" },
    notice: "到府評估時請家屬陪同",

    partnership: "formal",
    publicContact: { name: "何範例", phone: "02-0000-0006", emailOrLine: "LINE：demo_repair" },
    adminContact: SAME_AS_PUBLIC,
    followUpMethods: ["provider_contact"],
    followUpOther: null,
    links: ["https://example.com/demo-repair"],

    keywords: ["居家安全", "扶手", "修繕", "防跌"],
    scenarios: "適合家中曾跌倒、浴室或樓梯缺少扶手的獨居長者",
  },

  // 5. 中和｜紅燈｜正式合作｜常態每週 → 探索頁不顯示（風險紅燈）
  {
    id: "d3a1f0b2-1c4e-4a6b-8d2f-0a1b2c3d4e07",
    isDemo: true,
    code: "Res005",
    verifiedBy: { type: "team", name: "王示範" },
    lastVerifiedAt: "2026-07-01",
    nextVerifyAt: "2027-01-01",
    status: "active",
    pauseReason: null,
    resumeAt: null,
    seasonalNote: null,
    createdAt: "2025-05-01T09:00:00+08:00",
    updatedAt: "2026-07-01T09:00:00+08:00",

    name: "範例就醫陪伴接送服務",
    organization: "範例志工車隊",
    description: "志工駕駛自用車接送行動不便者往返醫院門診，並陪同掛號、領藥。",
    prescriptionTypes: ["basic_support"],
    needTags: ["transport"],
    needTagOther: null,
    staff: [
      { name: "蔡示範", role: "志工駕駛", license: "職業小客車駕照", experience: "接送服務 3 年" },
    ],
    capacity: { type: "limited", limit: 6 },
    availability: { type: "realtime", slots: 2, nextBatch: null },
    schedule: {
      type: "regular",
      frequency: "weekly",
      weekdays: [1, 2, 3, 4, 5],
      monthDays: [],
      startTime: "08:00",
      endTime: "17:00",
    },
    placeName: "範例志工車隊調度站",
    address: { zip: "235", city: "新北市", district: "中和區", detail: "示範路 66 巷 2 號" },
    geo: { lat: 24.9965, lng: 121.4935 },

    riskLevel: "red",
    riskCriteria: {
      management: "yellow",
      insurance: "red",
      environment: "green",
      complaints: "yellow",
      staffQualification: "green",
    },
    highRisk: { isHighRisk: false, types: [] },
    riskChangeNote: "車輛未投保乘客責任險，且有一件遲到投訴，由黃燈調整為紅燈，持續追蹤",

    ageGroups: ["senior"],
    identities: ["disability", "chronic"],
    identityOther: null,
    notSuitableFor: "需使用輪椅上下車或擔架者",
    participation: "registration",
    participationOther: null,
    languages: ["mandarin", "taiwanese"],
    indigenousTribe: null,
    languageOther: null,
    transport: ["shuttle"],
    transportNote: { publicTransit: null, shuttle: "到府接送至醫院門口", other: null },
    accessibility: ["senior_friendly"],
    accessibilityOther: null,
    fee: { type: "paid", detail: "每趟油資 100 元" },
    notice: "請於 3 天前預約，並提供門診時間",

    partnership: "formal",
    publicContact: { name: "蔡示範", phone: "02-0000-0007", emailOrLine: "demo07@example.com" },
    adminContact: SAME_AS_PUBLIC,
    followUpMethods: ["manager_contact"],
    followUpOther: null,
    links: ["https://example.com/demo-ride"],

    keywords: ["就醫", "接送", "陪診", "交通"],
    scenarios: "適合行動不便、家人無法陪同回診的長者",
  },

  // 6. 臺北文山｜綠燈｜合作尚未確認｜單次性｜社區活動引導 → 探索頁不顯示（合作未確認）
  {
    id: "d3a1f0b2-1c4e-4a6b-8d2f-0a1b2c3d4e09",
    isDemo: true,
    code: "Res006",
    verifiedBy: { type: "team", name: "林示例" },
    lastVerifiedAt: "2026-09-01",
    nextVerifyAt: "2026-12-01",
    status: "active",
    pauseReason: null,
    resumeAt: null,
    seasonalNote: null,
    createdAt: "2026-09-01T10:00:00+08:00",
    updatedAt: "2026-09-01T10:00:00+08:00",

    name: "範例森林療癒散步",
    organization: "範例自然生態學會",
    description: "由自然解說員帶領於近郊步道慢步、靜心與自然觀察，結尾有分享與靜思時間。",
    prescriptionTypes: ["health", "social"],
    needTags: ["nature", "spiritual", "exercise"],
    needTagOther: null,
    staff: [
      { name: "江範本", role: "自然解說員", license: "森林療癒指導員", experience: "步道解說 9 年" },
    ],
    capacity: { type: "limited", limit: 25 },
    availability: { type: "available", slots: 10, nextBatch: null },
    schedule: { type: "once", date: "2026-11-01", startTime: "08:30", endTime: "11:30" },
    placeName: "範例山步道登山口",
    address: { zip: "116", city: "臺北市", district: "文山區", detail: "示範路四段 1 號旁" },
    geo: { lat: 24.989, lng: 121.57 },

    riskLevel: "green",
    riskCriteria: CRITERIA_ALL_GREEN,
    highRisk: { isHighRisk: false, types: [] },
    riskChangeNote: "首次評估，五項條件皆為綠燈",

    ageGroups: ["all"],
    identities: ["all"],
    identityOther: null,
    notSuitableFor: "無法步行 2 公里者",
    participation: "registration",
    participationOther: null,
    languages: ["mandarin"],
    indigenousTribe: null,
    languageOther: null,
    transport: ["public_transit", "parking"],
    transportNote: { publicTransit: "公車範例站下車步行 5 分鐘", shuttle: null, other: null },
    accessibility: ["gender_friendly"],
    accessibilityOther: null,
    fee: { type: "free", detail: null },
    notice: "請穿著長袖長褲與防滑鞋，雨天取消",

    partnership: "unconfirmed",
    publicContact: { name: "江範本", phone: "02-0000-0009", emailOrLine: "demo09@example.com" },
    adminContact: SAME_AS_PUBLIC,
    followUpMethods: ["manager_contact"],
    followUpOther: null,
    links: ["https://example.com/demo-forest"],

    keywords: ["森林", "散步", "靜心", "自然"],
    scenarios: "適合壓力大、想到戶外走走放鬆心情的民眾",
  },
];
